[package]
name = "dupelink"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"

[dependencies]
uring-async = { path = "uring-async" }
rustix = { version = "0.38.34", features = ["fs"] }
lexopt = "0.3.0"
